version: '3'
services:
  alice:
    platform: linux/amd64
    image: acapy-run
    build:
      context: .
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 3001:3001
    volumes:
      - ./aries_cloudagent:/usr/src/app/aries_cloudagent:z
    command: >
      start
        -it http 0.0.0.0 3000 -ot http -e http://alice:3000
        --admin 0.0.0.0 3001 --admin-insecure-mode
        --wallet-type askar
        --wallet-name default
        --wallet-key test
        --auto-provision
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --tails-server-base-url http://tails:6543
        --log-level debug
    healthcheck:
      test: ["CMD-SHELL", "python", "healthcheck.py", "http://localhost:3001/status/live"]
      start_period: 10s
      interval: 3s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started

  bob:
    platform: linux/amd64
    image: acapy-run
    ports:
      - 3005:3005
    volumes:
      - ./aries_cloudagent:/usr/src/app/aries_cloudagent:z
    command: >
      start
        -it http 0.0.0.0 3004 -ot http -e http://bob:3004
        --admin 0.0.0.0 3005 --admin-insecure-mode
        --wallet-type askar
        --wallet-name default
        --wallet-key test
        --auto-provision
        --genesis-url https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
        --tails-server-base-url http://tails:6543
        --log-level debug
    healthcheck:
      test: ["CMD-SHELL", "python", "healthcheck.py", "http://localhost:3005/status/live"]
      start_period: 10s
      interval: 3s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started

  tails:
    platform: linux/amd64
    image: ghcr.io/indicio-tech/tails-server:sha-3d2feb2
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://raw.githubusercontent.com/Indicio-tech/indicio-network/main/genesis_files/pool_transactions_testnet_genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO

  tests:
    platform: linux/amd64
    image: anoncreds-test
    build:
      context: .
      dockerfile: ./docker/Dockerfile.anoncreds-test
    environment:
      ALICE: "http://alice:3001"
      BOB: "http://bob:3005"
    volumes:
      - ./anoncreds_test.py:/usr/src/app/anoncreds_test.py:z
    depends_on:
      alice:
        condition: service_healthy
      bob:
        condition: service_healthy
