name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    uses: ./.github/workflows/tests.yml
    with:
      python-version: ${{ matrix.python-version }}

  tests-indy:
    name: Tests (Indy)
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    uses: ./.github/workflows/tests-indy.yml
    with:
      python-version: ${{ matrix.python-version }}
      indy-version: "1.16.0"
