name: Nightly Tests (Indy)
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  indy_version: 1.16.0

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    uses: ./.github/workflows/tests-indy.yml
    with:
      python-version: ${{ matrix.python-version }}
      indy-version: ${{ env.indy_version }}
