name: Tests (Indy)
on:
  pull_request:

env:
  INDY_VERSION: 1.16.0

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Gather image info
        id: info
        run: |
          echo "::set-output name=indy-version::${{env.INDY_VERSION}}"

      - name: Cache image layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-test
          key: ${{ runner.os }}-buildx-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-test-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build test image
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          file: docker/Dockerfile.indy
          target: acapy-test
          tags: acapy-test:latest
          build-args: |
            python_version=${{ matrix.python-version }}
            indy_version=${{ steps.info.outputs.indy-version }}
          cache-from: type=local,src=/tmp/.buildx-cache-test
          cache-to: type=local,dest=/tmp/.buildx-cache-test-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-test
          mv /tmp/.buildx-cache-test-new /tmp/.buildx-cache-test

      - name: Run pytest
        run: |
          docker run --rm -it acapy-test:latest
