name: Tests
on:
  pull_request:

jobs:
  image:
    name: Test image publishing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    outputs:
      repo-owner: ${{ steps.repo-owner.outputs.owner-lc }}

    steps:
      - uses: actions/checkout@v3

      - name: Image built?
        id: image-built
        uses: actions/cache@v2
        with:
          path: ~/.image
          key: ${{ matrix.python-version }}-${{ hashFiles('requirements*.txt') }}

      - name: lowercase repo owner name
        id: repo-owner
        run: |
          echo "::set-output name=owner-lc::${GITHUB_REPOSITORY_OWNER,,}"

      - name: Setup Image Metadata
        if: steps.image-built.outputs.cache-hit != 'true'
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/acapy-test
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ hashFiles('requirements*.txt') }}
            type=raw,value=py${{ matrix.python-version }}

      - name: Log in to the GitHub Container Registry
        if: steps.image-built.outputs.cache-hit != 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.image-built.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v1

      - name: Build and Push to Docker ghcr.io
        if: steps.image-built.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: docker/Dockerfile.test
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  tests:
    name: Tests
    needs: image
    runs-on: ubuntu-latest
    container: ghcr.io/${{ needs.image.outputs.repo-owner }}/acapy-test:py${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Run pytest
        run: pytest
